# Generated by Django 4.0 on 2022-10-19 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilamentInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams_filament_consumed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FilamentMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('METERS_PER_GRAM', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Number of meters of Filament in one gram of Filament')),
                ('polymer_type', models.CharField(max_length=255, verbose_name='Polymer type of the Filament (PLA, PLA+, PET, PETG, etc.)')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ModelPrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of 3D Print Model')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prints', to='accounts.customuser')),
                ('filament_instance', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='print', to='prints.filamentinstance')),
            ],
        ),
        migrations.CreateModel(
            name='FilamentRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rolls', to='prints.manufacturer')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rolls', to='prints.filamentmaterial')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rolls', to='accounts.customuser')),
            ],
        ),
        migrations.AddField(
            model_name='filamentinstance',
            name='filament_roll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='prints.filamentroll'),
        ),
    ]
