# Generated by Django 4.0 on 2022-10-17 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filamentmaterial',
            old_name='type',
            new_name='polymer_type',
        ),
    ]
