# Generated by Django 4.0 on 2022-10-07 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filamentinstance',
            name='filament_roll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='prints.filamentroll'),
        ),
    ]
