# Generated by Django 4.0 on 2022-10-07 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('prints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelprint',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prints', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='modelprint',
            name='filament_instance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='print', to='prints.filamentinstance'),
        ),
        migrations.AddField(
            model_name='filamentinstance',
            name='filament_roll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prints.filamentroll'),
        ),
    ]
