# Generated by Django 4.0 on 2022-10-16 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filamentinstance',
            old_name='filament_consumed',
            new_name='grams_filament_consumed',
        ),
    ]
