# Generated by Django 4.0 on 2022-10-07 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0002_alter_filamentinstance_filament_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filamentroll',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rolls', to='prints.manufacturer'),
        ),
    ]
