# Generated by Django 4.0 on 2022-09-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0002_filament'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
