# Generated by Django 4.0 on 2022-10-07 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('prints', '0003_alter_filamentroll_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='filamentroll',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rolls', to='users.customuser'),
        ),
    ]
