# Generated by Django 4.0 on 2022-09-30 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0004_modelprint_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelprint',
            name='filament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prints', to='prints.filament'),
        ),
    ]
