# Generated by Django 4.0 on 2022-10-08 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0004_filamentroll_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filamentroll',
            old_name='creator',
            new_name='owner',
        ),
    ]
