# Generated by Django 4.0 on 2022-10-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0004_filamentroll_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filamentinstance',
            name='filament_consumed',
            field=models.IntegerField(default=0),
        ),
    ]
