# Generated by Django 4.0 on 2022-09-30 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0005_modelprint_filament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelprint',
            name='filament',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='prints', to='prints.filament'),
            preserve_default=False,
        ),
    ]
