# Generated by Django 4.0 on 2022-10-02 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0009_rename_filament_filamentinstance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelprint',
            old_name='filament',
            new_name='filament_instance',
        ),
    ]
