# Generated by Django 4.0 on 2022-10-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0010_rename_filament_modelprint_filament_instance'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilamentRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='filamentinstance',
            old_name='material',
            new_name='filament_roll',
        ),
    ]
