# Generated by Django 4.0 on 2022-10-02 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0011_filamentroll_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filamentinstance',
            name='filament_roll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prints.filamentroll'),
        ),
    ]
