# Generated by Django 4.0 on 2022-10-02 07:11

from django.db import migrations, models
import prints.models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0012_alter_filamentinstance_filament_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filamentinstance',
            name='filament_roll',
            field=models.ForeignKey(on_delete=models.PROTECT, to='prints.filamentroll'),
        ),
    ]
