# Generated by Django 4.0 on 2022-10-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0013_alter_filamentinstance_filament_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='filamentinstance',
            name='material',
            field=models.CharField(default='Potato Starch', max_length=255),
            preserve_default=False,
        ),
    ]
