# Generated by Django 4.0 on 2022-10-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0014_filamentinstance_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filamentinstance',
            name='material',
        ),
        migrations.AddField(
            model_name='filamentinstance',
            name='filament_consumed',
            field=models.FloatField(default=0),
        ),
    ]
