# Generated by Django 4.0 on 2022-12-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_supermaker',
            field=models.BooleanField(default=False, help_text='Designates whether the user is a Supermaker. Supermakers may gain special privileges in the future.'),
        ),
    ]
